BLXV-65 (8.34) Remove the need for gda[log|servers|client]-dummy commands.
Add support for GDA_MODE environment variable, which should be set in
gda_environment.sh on a beamline workstation, but not set elsewhere.

diff --git a/configurations/i15-config/bin/gdaservers b/configurations/i15-config/bin/gdaservers
--- a/configurations/i15-config/bin/gdaservers
+++ b/configurations/i15-config/bin/gdaservers
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+if [ -z $GDA_MODE ] ; then
+  GDA_MODE=dummy
+fi
+
 echo Ensure the Log panel is running...
 gdalog
 
@@ -7,67 +11,10 @@ echo
 echo Making sure we want to restart GDA servers now...
 echo
 
-zenity --title "Are you sure?" --question --text "Are you sure you want to restart the $BEAMLINE GDA servers?" --window-icon=question
+zenity --title "Are you sure?" --question --text "Are you sure you want to restart the $GDA_MODE $BEAMLINE GDA servers?" --window-icon=question
 SURE=$?
 if [ $SURE == 1 ]; then # 0=Ok, 1=Cancel
   exit
-fi
-
-echo Fix the OD PC issues
-echo
-nohup rdesktop -T "OD PC" -5 -a 16 -u i15detector -p \!i15d3t3ct0r# -d DIAMOND -k en-gb -g 1850x1150 i15-rubiccd01 > /dev/null &
-
-WINDOWTITLE="Please restart IS"
-(sleep 5; wmctrl -a "$WINDOWTITLE")& # bring zenity to front after 5 secs.
-zenity --title "$WINDOWTITLE" --info --text "\
-	Due to a problem with the Oxford Diffraction\r
-	software, the GDA server cannot reconnect to the\r
-	IS application automatically when it restarts.\n
-	When this happens the fast shutter will not open\r
-	for *any* detector.\n
-	To correct this, please use the remote desktop\r
-	just opened ('OD PC' in your Window List) to:\n
-	1. Close the IS application ('CMD: root' in the task bar).\n
-	2. Restart the IS application (by clicking on the\r
-	    yellow diffractometer icon in the quick launch\r
-	    bar, near the start menu, which has the tooltip\r
-	    'Shortcut to is_win32_2.1.1936_18A_Release.exe'.\n
-	3. Disconnect from the OD PC by closing the 'OD PC'\r
-	    window.\n
-	When you have done this, click Ok and the GDA server\r
-	restart will continue."
-
-##This is an example script file to restart GDA server from a remote client
-##This requires generation of ssh keys and copying the public key to the authorized_keys file in the server
-##Please refer to the document howtoSSH.txt for key generation.
-##To use this script change the key file path, user name and the server machine name
-
-echo
-echo Checking for an old known_host key
-
-KNOWN_HOST="i15-control.diamond.ac.uk,172.23.115.32 ssh-rsa"
-KNOWN_HOST_OLDKEY="AAAAB3NzaC1yc2EAAAABIwAAAQEAzJZZ0/24hraQavEZEHlG+u8Aitw43YzDLUTd9i/BHHS5KuIiLUgaQV/gn2EnE3Oscd9u/JFUmKUNZESUTYGe6s07/YrdbpGZavBJvLrHkmmtFfOCCVemILZJDqzG2iIxqz9MVznMVf5ctSbqCOE1z+aR/AfcWUuP2LsrRtZ1mQzjRV21Fy+NGknPQ8d4aOY7phQfWQLqWKDM63JdCP3ZcnIWA+53QUt5Trrjty8fG/aah4at8gMyvZjAQHrR/CcVA2MB9OjkaTs2gCm0nNXGKxKJk4/pXCwAXYoWKLynSiHMaz1xl7hNjzTPvKzM65F60pigIz3137PKuXv8WWBZDQ=="
-KNOWN_HOST_KEY="AAAAB3NzaC1yc2EAAAABIwAAAQEAukEds96jTVQGxMIemckxTvlFRj39hvgx3z2hkKVLvIhMMVI8BQrq4pH+Lgh7fofYgCs6FRs6arqF2Sa6Fcvlm2228bf5Xiimieon1cZi+Ntacmayi2xVR4Dx+PYmb/vbyDwHRHsWxWrtSYz+40HEeXguTEsD1tEm82xAK3Jbc12ew1/VeTpDY9i+gkFRtNulZLc6UHB75G1sHAlGKhxtbp7pLT+AQVSIl9Mx5ruRO/CmWsMVh2HFGhpgsH0amuFcTUQTopjq2pKqP2y0gUN8ZXGXBxn2n+PnGRKV7gU0YSbTSpReUu14eV16W+VOseOM9M9oAvLb0cGoy9VAXTgnrQ=="
-
-grep "i15-control" ~/.ssh/known_hosts > 2&>1 /dev/null
-OK=$?	# 0 if ok, 2 if file doesn't exist, 1 if file doesn't contain pattern
-
-if [ $OK == 0 ]; then
-	grep $KNOWN_HOST_OLDKEY ~/.ssh/known_hosts > 2&>1 /dev/null
-	OLD=$? # 0 if ok, 2 if file doesn't exist, 1 if file doesn't contain pattern
-
-	if [ $OLD == 0 ]; then
-		echo Removing old known_host key
-		sed -i /i15-control/d ~/.ssh/known_hosts
-		OK=1
-	fi
-else
-	echo i15-control not in ~/.ssh/known_hosts, adding...
-fi
-
-# if known_host or file doesn't exist
-if [ $OK != 0 ]; then
-	echo $KNOWN_HOST $KNOWN_HOST_KEY >> ~/.ssh/known_hosts
 fi
 
 echo
@@ -76,15 +23,97 @@ echo
 echo "Keep this window open, and you will see a pop-up when the restart has completed"
 echo
 
-ssh  -i /dls_sw/i15/software/gda/workspace_git/gda-mt.git/configurations/i15-config/i15ssh.key gda2@i15-control.diamond.ac.uk
-OK=$?
-
-# 127 if ssh cannot run command, 0 if ran ok, maybe other values if remote command returns them
-
-if [ $OK != 0 ]; then
-  zenity --title "Error starting GDA Server" --error --text "Something went wrong starting GDA server. Please try logging out and back in again before contacting your GDA representative." 
-  exit
+if [ "$GDA_MODE" = "live" ]; then
+	
+	echo Fix the OD PC issues
+	echo
+	nohup rdesktop -T "OD PC" -5 -a 16 -u i15detector -p \!i15d3t3ct0r# -d DIAMOND -k en-gb -g 1850x1150 i15-rubiccd01 > /dev/null &
+	
+	WINDOWTITLE="Please restart IS"
+	(sleep 5; wmctrl -a "$WINDOWTITLE")& # bring zenity to front after 5 secs.
+	zenity --title "$WINDOWTITLE" --info --text "\
+		Due to a problem with the Oxford Diffraction\r
+		software, the GDA server cannot reconnect to the\r
+		IS application automatically when it restarts.\n
+		When this happens the fast shutter will not open\r
+		for *any* detector.\n
+		To correct this, please use the remote desktop\r
+		just opened ('OD PC' in your Window List) to:\n
+		1. Close the IS application ('CMD: root' in the task bar).\n
+		2. Restart the IS application (by clicking on the\r
+		    yellow diffractometer icon in the quick launch\r
+		    bar, near the start menu, which has the tooltip\r
+		    'Shortcut to is_win32_2.1.1936_18A_Release.exe'.\n
+		3. Disconnect from the OD PC by closing the 'OD PC'\r
+		    window.\n
+		When you have done this, click Ok and the GDA server\r
+		restart will continue."
+	
+	##This is an example script file to restart GDA server from a remote client
+	##This requires generation of ssh keys and copying the public key to the authorized_keys file in the server
+	##Please refer to the document howtoSSH.txt for key generation.
+	##To use this script change the key file path, user name and the server machine name
+	
+	echo
+	echo Checking for an old known_host key
+	
+	KNOWN_HOST="i15-control.diamond.ac.uk,172.23.115.32 ssh-rsa"
+	KNOWN_HOST_OLDKEY="AAAAB3NzaC1yc2EAAAABIwAAAQEAzJZZ0/24hraQavEZEHlG+u8Aitw43YzDLUTd9i/BHHS5KuIiLUgaQV/gn2EnE3Oscd9u/JFUmKUNZESUTYGe6s07/YrdbpGZavBJvLrHkmmtFfOCCVemILZJDqzG2iIxqz9MVznMVf5ctSbqCOE1z+aR/AfcWUuP2LsrRtZ1mQzjRV21Fy+NGknPQ8d4aOY7phQfWQLqWKDM63JdCP3ZcnIWA+53QUt5Trrjty8fG/aah4at8gMyvZjAQHrR/CcVA2MB9OjkaTs2gCm0nNXGKxKJk4/pXCwAXYoWKLynSiHMaz1xl7hNjzTPvKzM65F60pigIz3137PKuXv8WWBZDQ=="
+	KNOWN_HOST_KEY="AAAAB3NzaC1yc2EAAAABIwAAAQEAukEds96jTVQGxMIemckxTvlFRj39hvgx3z2hkKVLvIhMMVI8BQrq4pH+Lgh7fofYgCs6FRs6arqF2Sa6Fcvlm2228bf5Xiimieon1cZi+Ntacmayi2xVR4Dx+PYmb/vbyDwHRHsWxWrtSYz+40HEeXguTEsD1tEm82xAK3Jbc12ew1/VeTpDY9i+gkFRtNulZLc6UHB75G1sHAlGKhxtbp7pLT+AQVSIl9Mx5ruRO/CmWsMVh2HFGhpgsH0amuFcTUQTopjq2pKqP2y0gUN8ZXGXBxn2n+PnGRKV7gU0YSbTSpReUu14eV16W+VOseOM9M9oAvLb0cGoy9VAXTgnrQ=="
+	
+	grep "i15-control" ~/.ssh/known_hosts > 2&>1 /dev/null
+	OK=$?	# 0 if ok, 2 if file doesn't exist, 1 if file doesn't contain pattern
+	
+	if [ $OK == 0 ]; then
+		grep $KNOWN_HOST_OLDKEY ~/.ssh/known_hosts > 2&>1 /dev/null
+		OLD=$? # 0 if ok, 2 if file doesn't exist, 1 if file doesn't contain pattern
+	
+		if [ $OLD == 0 ]; then
+			echo Removing old known_host key
+			sed -i /i15-control/d ~/.ssh/known_hosts
+			OK=1
+		fi
+	else
+		echo i15-control not in ~/.ssh/known_hosts, adding...
+	fi
+	
+	# if known_host or file doesn't exist
+	if [ $OK != 0 ]; then
+		echo $KNOWN_HOST $KNOWN_HOST_KEY >> ~/.ssh/known_hosts
+	fi
+	
+	ssh  -i /dls_sw/i15/software/gda/workspace_git/gda-mt.git/configurations/i15-config/i15ssh.key gda2@i15-control.diamond.ac.uk
+	OK=$?
+	
+	# 127 if ssh cannot run command, 0 if ran ok, maybe other values if remote command returns them
+	
+	if [ $OK != 0 ]; then
+	  zenity --title "Error starting GDA Server" --error --text "Something went wrong starting GDA server. Please try logging out and back in again before contacting your GDA representative." 
+	  exit
+	fi
+else
+	
+	export GDA_ROOT=$(readlink -f $(dirname $0)/../../../../..)
+	#. $GDA_ROOT/workspace_git/gda-mt.git/configurations/mt-config/bin/gda_setup_env gda_servers_output
+	
+	GDA_VAR=$(readlink -f $GDA_ROOT/../var)
+	if [ -d $GDA_VAR ]; then
+		export OBJECT_SERVER_STARTUP_FILE=$GDA_VAR/object_server_startup_server_main
+		echo OBJECT_SERVER_STARTUP_FILE=$OBJECT_SERVER_STARTUP_FILE
+	else
+		echo ERROR: $GDA_VAR does not exist.
+		exit
+	fi
+	rm -f $OBJECT_SERVER_STARTUP_FILE
+	
+	#. $GDA_ROOT/workspace_git/gda-mt.git/configurations/$BEAMLINE-config/bin/GDA_StartServers --mode=dummy
+	GDA_StartServers --mode=dummy
+	
+	# look for the output file which will tell us when the servers have started
+	
+	lookForFile $OBJECT_SERVER_STARTUP_FILE
 fi
+
 #
 # wait for the remote command, which will look for the output file which will
 # tell us when the servers have started before returning, then display to the
