set BEAMLINE and GDA_MODE in optics_profile.sh and source it from gda launcher as there is no standard support in IT Linux system to support Lab workstation as beamline workstation, i.e. the profile is not loaded at users login.

diff --git a/configurations/optics-config/bin/gda b/configurations/optics-config/bin/gda
--- a/configurations/optics-config/bin/gda
+++ b/configurations/optics-config/bin/gda
@@ -1,6 +1,12 @@
 #!/bin/bash
 # Expects a parameter line that can be passed on to the gda python script
 export GDA_DEBUG=TRUE
+source ../etc/live/optics_profile.sh
+
+if [ ! -n "$BEAMLINE" ]; then
+  echo "ERROR: BEAMLINE not set" 1>&2
+  exit 1
+fi
 
 here_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 set -o nounset  # Turn on nounset
@@ -10,7 +16,7 @@ set -o errexit  # Turn on errexit
 export GDA_WORKSPACE_PARENT=$(readlink -f ${here_dir}/../../../../..)
 export GDA_WORKSPACE_GIT_NAME=$(basename $(readlink -f ${here_dir}/../../../..))  # will normally be "workspace_git", will always end with "_git"
 export GDA_INSTANCE_CONFIG_rel=${GDA_WORKSPACE_GIT_NAME}/gda-mt.git/configurations/${BEAMLINE}-config
-export GDA_GROUP_CONFIG_rel=${GDA_WORKSPACE_GIT_NAME}/gda-mt.git/configurations/i06-shared
+export GDA_GROUP_CONFIG_rel=${GDA_WORKSPACE_GIT_NAME}/gda-core.git/no-group
 export GDA_FACILITY_CONFIG_rel=${GDA_WORKSPACE_GIT_NAME}/gda-diamond.git/dls-config
 export GDA_CORE_CONFIG_rel=${GDA_WORKSPACE_GIT_NAME}/gda-core.git/core-config
 
