JEEP-48 - Changed so that the module system works correctly with i12. Changed dummyAd.xml to match constructor changes in Java. Changed default perspective to "Scripts" perspective. Client deployment now created in x86_64 architecture. install.sh launchers changed as they used to work in RHEL4 but not in RHEL5

diff --git a/configurations/i12-config/bin/GDA_RemoteStart_Lin b/configurations/i12-config/bin/GDA_RemoteStart_Lin
--- a/configurations/i12-config/bin/GDA_RemoteStart_Lin
+++ b/configurations/i12-config/bin/GDA_RemoteStart_Lin
@@ -10,6 +10,13 @@ then
   echo "Please set BEAMLINE environment variable."
   exit 1
 fi
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot scd ..ource /etc/profile.d/modules.sh"	
+	exit 1
+fi
 
 #echo "Kill all GDA Clients running locally"
 #gda --stop --verbose client
diff --git a/configurations/i12-config/bin/GDA_StartClient b/configurations/i12-config/bin/GDA_StartClient
--- a/configurations/i12-config/bin/GDA_StartClient
+++ b/configurations/i12-config/bin/GDA_StartClient
@@ -1,6 +1,13 @@
 #!/bin/bash
 
-. /dls_sw/i12/software/gda/builder/set_tools.sh
+
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot source /etc/profile.d/modules.sh"	
+	exit 1
+fi
 
 JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=256m" `dirname $0`/gda rcpclient --rcp_image=/$SOFTWAREFOLDER/$BEAMLINE/software/gda/client/gda  --restart  $@ #--debug --debugport=8003  --suspend=y
 #/$SOFTWAREFOLDER/$BEAMLINE/software/gda/client/gda -vmargs 
diff --git a/configurations/i12-config/bin/GDA_StartServers_localhost b/configurations/i12-config/bin/GDA_StartServers_localhost
--- a/configurations/i12-config/bin/GDA_StartServers_localhost
+++ b/configurations/i12-config/bin/GDA_StartServers_localhost
@@ -2,6 +2,13 @@
 
 #if lustre is down - set the GDA_DATADIR to scratch (i.e uncomment the below line)
 #export GDA_DATADIR=/scratch;
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot scd ..ource /etc/profile.d/modules.sh"	
+	exit 1
+fi
 
 /dls_sw/i12/software/gda_versions/gda_8.22/plugins/uk.ac.gda.core/bin/gda  --smart --trace --config=/dls_sw/i12/software/gda_versions/gda_8.22/i12-config --restart --mode=localhost nameserver
 /dls_sw/i12/software/gda_versions/gda_8.22/plugins/uk.ac.gda.core/bin/gda  --smart --trace --config=/dls_sw/i12/software/gda_versions/gda_8.22/i12-config --restart --mode=localhost logserver
diff --git a/configurations/i12-config/bin/GDA_Start_GTK b/configurations/i12-config/bin/GDA_Start_GTK
--- a/configurations/i12-config/bin/GDA_Start_GTK
+++ b/configurations/i12-config/bin/GDA_Start_GTK
@@ -12,6 +12,14 @@ fi
 rm -f /$SOFTWAREFOLDER/$BEAMLINE/var/object_server_startup_server_*
 ssh  -i /$SOFTWAREFOLDER/$BEAMLINE/${BEAMLINE}ssh.key gda@${BEAMLINE}-control.diamond.ac.uk 
 
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot scd ..ource /etc/profile.d/modules.sh"	
+	exit 1
+fi
+
 echo "Restarting the GDA Server, please wait..."
 #removing the popup window because it's not working properly
 echo "Keep this window open, and you will see a pop-up when the restart has completed"
