LOCALHOST Configuration corrections.

diff --git a/configurations/i12-config/bin/GDA_StartServers_localhost b/configurations/i12-config/bin/GDA_StartServers_localhost
--- a/configurations/i12-config/bin/GDA_StartServers_localhost
+++ b/configurations/i12-config/bin/GDA_StartServers_localhost
@@ -17,3 +17,32 @@ fi
 export JAVA_OPTS="-Xms128m -Xmx2056m -XX:MaxPermSize=256m -XX:+DisableExplicitGC"
 /dls_sw/i12/software/gda_git/gda-core.git/uk.ac.gda.core/bin/gda  --smart --trace --config=/dls_sw/i12/software/gda_git/gda-dls-beamlines-i12.git/i12 --debug -p 8001 --restart -v --mode=localhost objectserver
  
+#!/bin/bash
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot scd ..ource /etc/profile.d/modules.sh"	
+	exit 1
+fi
+
+#`dirname $0`/gda nameserver --stop $@
+#`dirname $0`/gda logserver --stop $@
+#`dirname $0`/gda eventserver --stop $@
+#`dirname $0`/gda objectserver --stop $@
+
+#echo "start name server"
+#`dirname $0`/gda nameserver $@
+#echo "start log server"
+#`dirname $0`/gda logserver $@
+#echo "start event server"
+#`dirname $0`/gda eventserver $@
+#echo "start object server"
+#JAVA_OPTS="-Xms128m -Xmx1024m" `dirname $0`/gda objectserver  --profile=main --smart --trace --mode=localhost --debug --debugport=8002 $@ #--suspend=y
+
+export JAVA_OPTS="-Xms128m -Xmx1024m -XX:MaxPermSize=128m -XX:+DisableExplicitGC"
+#/dls_sw/i12/software/gda_versions/gda_trunk/plugins/uk.ac.gda.core/bin/gda  --smart --trace --config=/dls_sw/i12/software/gda_versions/gda_trunk/i12-config --debug -p 8001 --restart -v --mode=live servers
+/dls_sw/i12/software/gda_git/gda-core.git/uk.ac.gda.core/bin/gda  --smart --trace --config=/dls_sw/i12/software/gda_git/gda-dls-beamlines-i12.git/i12 --debug -p 8001 --restart -v --mode=localhost servers
+# > $LOGFILE 2>&1 &
+ 
+ 
