missing file and updated files from 8.38

diff --git a/i09-config/bin/GDA_StartLogServer b/i09-config/bin/GDA_StartLogServer
--- a/i09-config/bin/GDA_StartLogServer
+++ b/i09-config/bin/GDA_StartLogServer
@@ -1,7 +1,13 @@
 #!/bin/bash
 . "/$SOFTWAREFOLDER/$BEAMLINE/software/gda/config/bin/gda_environment.sh"
 
-. /dls_sw/$BEAMLINE/software/gda/workspace_git/gda-diamond.git/dls-config/bin/loadjava.sh
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot scd ..ource /etc/profile.d/modules.sh"	
+	exit 1
+fi
 
 echo "starting GDA Log Server"
 echo `dirname $0`/gda_command logserver --restart $@
diff --git a/i09-config/bin/GDA_StartRCP b/i09-config/bin/GDA_StartRCP
--- a/i09-config/bin/GDA_StartRCP
+++ b/i09-config/bin/GDA_StartRCP
@@ -10,10 +10,16 @@ notify-send -t 10000 "GDA RCP Client is starting..."
 
 . /$SOFTWAREFOLDER/$BEAMLINE/software/gda/config/bin/gda_environment.sh
 
-. /dls_sw/$BEAMLINE/software/gda/workspace_git/gda-diamond.git/dls-config/bin/loadjava.sh
+if [ -f "/etc/profile.d/modules.sh" ]; then
+	. /etc/profile.d/modules.sh	
+	module load java/gda
+else
+	echo "cannot source /etc/profile.d/modules.sh"	
+	exit 1
+fi
 
 # Start log panel if not already started
-LOGPANEL=$(ps -ef | grep LogPanel | grep -v grep)
+LOGPANEL=$(ps -ef | grep gdalogpanel | grep -v grep)
 if [ "X$LOGPANEL" == "X" ] ; then
 	nohup GDA_StartLogPanel 2>/dev/null &
 else
